### ISSUE TITLE
Open created files

### ISSUE THREAD

**Issue by BraunTom** [LeonMatthes/cmps#1]
Add a command line flag to open the files you created with the tool with the standard tool the platform/user has for the special file extension

**Comment by LeonMatthes** [comment]
With version 0.3.3, there is a new option `--stdout` that allows you to print the template to stdout, instead of writing it to a file.
This makes it relatively easy to integrate into editors, like vim or nvim.

(Neo-)Vim example:
``` vim
function Compose()
  " Check that the buffer is empty and that it has a filename
  if wordcount().bytes == 0 && len(getreg("%")) > 0
    0r! cmps --stdout %
  endif
endfunction

autocmd BufEnter * call Compose()
```

So instead of `cmps --open test.h`, you can simply use `nvim test.h` to create the file and automatically fill it with the template content.
The advantage of this approach is that using the template can also be undone, if you for some reason don't want to use the template for this specific file.

Would this be sufficient for your use-case?
